export const data = {
  elements: [
    {
      icon: 'input',
      element: {
        requared: false,
        label: 'Input',
        position: 'center',
        textColor: '#6E6E6E',
        lableColor: '#6E6E6E',
        background: '#FBFBFB',
        type: 'input',
        width: 200,
        height: 25,
        fontSize: 20,
        fontWeight: 'lighter',
        borderWidth: 2,
        borderColor: '#6E6E6E',
        borderType: 'solid',
        values: '[]',
      },
    },
    {
      icon: 'edit_square',
      element: {
        requared: false,
        label: 'textarea',
        position: 'center',
        textColor: '#6E6E6E',
        lableColor: '#6E6E6E',
        background: '#FBFBFB',
        type: 'textarea',
        width: 200,
        height: 25,
        fontSize: 20,
        fontWeight: 'lighter',
        borderWidth: 2,
        borderColor: '#6E6E6E',
        borderType: 'solid',
        values: '[]',
      },
    },
    {
      icon: 'check_box_outline_blank',
      element: {
        content: 'button',
        position: 'center',
        textColor: '#6E6E6E',
        background: '#FBFBFB',
        type: 'button',
        width: 100,
        height: 40,
        fontSize: 20,
        fontWeight: 'lighter',
        borderWidth: 2,
        borderColor: '#6E6E6E',
        borderType: 'solid',
        values: '[]',
      },
    },
    {
      icon: 'check_box',
      element: {
        label: 'checkbox',
        position: 'center',
        lableColor: '#6E6E6E',
        type: 'checkbox',
        width: 20,
        height: 20,
        fontSize: 20,
        fontWeight: 'lighter',
        values: '[]',
      },
    },
    {
      icon: 'text_fields',
      element: {
        content: 'text',
        position: 'center',
        textColor: '#6E6E6E',
        type: 'text',
        width: 100,
        height: 20,
        fontSize: 20,
        fontWeight: 'lighter',
        values: '[]',
      },
    },
    {
      icon: 'fact_check',
      element: {
        requared: false,
        label: 'select',
        type: 'select',
        position: 'center',
        textColor: '#6E6E6E',
        lableColor: '#6E6E6E',
        background: '#FBFBFB',
        values: '[{"value": "value" , "id": 1 , "elementId": 2}]',
        width: 200,
        height: 25,
        fontSize: 20,
        fontWeight: 'lighter',
      },
    },
  ],
};
